# fly.toml app configuration file generated for aim4-backend on 2026-06-24T23:51:58+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aim4-backend'
primary_region = 'iad'

[build]

[env]
  AIM4_API_PORT = '8080'
  AIM4_HOST = '0.0.0.0'

[processes]
  app = 'node server/index.js'

[http_service]
  processes = ['app']
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 200
    soft_limit = 150

  [[http_service.checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
