[phases.setup]
aptPkgs = [
  "...",
  "xvfb",
  "xauth",
  "unar",
  "libarchive-tools",
  "fonts-noto-color-emoji",
  "fonts-freefont-ttf",
  "fonts-unifont",
  "fonts-ipafont-gothic",
  "fonts-wqy-zenhei",
  "fonts-tlwg-loma-otf"
]
