// ---------------------------------------------------------------------------
// replays/duels/duelModelParams.js
// GENERATED by scripts/train-duel-model.mjs. Do not edit by hand.
//
// Fitted against 2505 labelled duels from the parsed demos in sampledemos/.
// Validation is held out by demo, so no fight contributes to both halves.
//
//   validation log loss  0.5634   (a coin flip scores 0.6931)
//   validation exam      2.59 points per duel
//   validation brier     0.1898
//   training log loss    0.5446
//
// To refit:
//   node scripts/fetch-zone-networks.mjs
//   node scripts/extract-duel-episodes.mjs
//   node scripts/train-duel-model.mjs --generations 200 --export
// ---------------------------------------------------------------------------

import { fromNamed } from './paramSpec.js';
import { primeRuntimeParams, runtimeParams } from '../models/runtimeParams.js';

export const DUEL_MODEL_PARAMS = {
  specHash: '23582734',
  trainedOn: 2505,
  validation: {
    logLoss: 0.56337,
    exam: 2.5917,
    brier: 0.189844
  },
  values: {
    crossW: 3.209749,
    crossSigma: 48.285637,
    crossPow: 0.388281,
    infoW: 0,
    infoTau: 1.516022,
    valW: 0.466658,
    diffW: 0,
    diffSat: 4,
    catPistol: -0.422786,
    catSmg: 0.135975,
    catShotgun: 3,
    catRifle: -0.071276,
    catSniper: -0.23857,
    catLmg: 0.1,
    catKnife: 0.227627,
    catOther: -2,
    dist_pistol_0: 0.301323,
    dist_pistol_1: -0.09389,
    dist_pistol_2: -0.171117,
    dist_pistol_3: 1.223552,
    dist_smg_0: 0.256217,
    dist_smg_1: -0.561302,
    dist_smg_2: -0.760548,
    dist_smg_3: -2.5,
    dist_shotgun_0: 2.5,
    dist_shotgun_1: 2.5,
    dist_shotgun_2: 0,
    dist_shotgun_3: 0,
    dist_rifle_0: -0.079804,
    dist_rifle_1: -0.132085,
    dist_rifle_2: -0.331519,
    dist_rifle_3: 0.897099,
    dist_sniper_0: -0.860681,
    dist_sniper_1: 0.14938,
    dist_sniper_2: 0.427148,
    dist_sniper_3: -0.272225,
    move_pistol: -0.136304,
    move_smg: -0.541263,
    move_shotgun: 0.5,
    move_rifle: -0.519162,
    move_sniper: -0.94986,
    hpW: 1.279529,
    armorW: 0.325805,
    oneTapW: -0.07481,
    noHelmetW: 0.129248,
    flashW: 0.027397,
    flashPow: 2.137778,
    reloadW: 0,
    lowMagW: 0.612144,
    cycleW: 0.415756,
    scopedW: 0.798412,
    duckW: 0.15,
    airW: -0.8,
    lambdaEnemy: 0.471236,
    threatSat: 6,
    countPow: 1.224595,
    spreadW: 0,
    spreadSigma: 64.811271
  }
};

let cached = null;

// Weights fitted on the server against the whole replay library beat the ones
// compiled into this bundle, which were fitted on a sample. The fetch is
// started once, and the cached vector is dropped when better weights land so
// the next prediction picks them up. Until then, and on any failure, the values
// below are used unchanged.
primeRuntimeParams('duel', DUEL_MODEL_PARAMS.specHash, () => {
  cached = null;
});

/** The fitted parameter vector, in paramSpec order. */
export function paramVector() {
  if (!cached) {
    const live = runtimeParams('duel');
    const useLive = live && live.specHash === DUEL_MODEL_PARAMS.specHash;
    cached = fromNamed(useLive ? live.values : DUEL_MODEL_PARAMS.values);
  }
  return cached;
}
