// ---------------------------------------------------------------------------
// replays/rounds/roundModelParams.js
// GENERATED by scripts/train-round-model.mjs. Do not edit by hand.
//
// Fitted against 937 rounds from the parsed demos in sampledemos/.
// Validation is held out by demo, so no round contributes to both halves.
//
//   validation log loss  0.4397   (a coin flip scores 0.6931)
//   validation brier     0.1481
//   training log loss    0.3969
//
// The three exams, on held-out demos:
//   early to mid    loss 0.5427
//   mid to late     loss 0.4332
//   10s before end  loss 0.1575
//
// To refit:
//   node scripts/fetch-zone-networks.mjs
//   node scripts/extract-round-snapshots.mjs
//   node scripts/train-round-model.mjs --generations 60 --export
// ---------------------------------------------------------------------------

import { fromNamed } from './roundParamSpec.js';
import { primeRuntimeParams, runtimeParams } from '../models/runtimeParams.js';

export const ROUND_MODEL_PARAMS = {
  specHash: '293afae9',
  trainedOn: 937,
  // Per-phase Platt scale, p' = sigmoid(a * logit + b). All ones and zeroes
  // means the fit did not beat the raw model on held-out loss and was refused.
  calibration: {
    early: { a: 1.095786, b: -0.02274 },
    mid: { a: 0.956348, b: -0.024384 },
    late: { a: 0.943842, b: -0.003057 }
  },
  validation: {
    logLoss: 0.439708,
    brier: 0.148136,
    exam: 4.3537
  },
  exams: {
    early: { logLoss: 0.542732, exam: 3.1086, n: 186 },
    mid: { logLoss: 0.433215, exam: 4.6543, n: 160 },
    final: { logLoss: 0.15753, exam: 7.7397, n: 186 }
  },
  values: {
    bias: -0.400541,
    map_ANC: -0.099482,
    map_ANU: -0.508567,
    map_CCH: -0.063732,
    map_DD2: -0.26616,
    map_INF: -0.25075,
    map_MIR: 0.008436,
    manW: 3.448047,
    manTau: 2.545974,
    manPow: 1.528697,
    manShareW: 3.769728,
    hpW: 2.236501,
    lastManW: 0.222259,
    duelW: 2.329397,
    duelTau: 9.498221,
    equipW: 8.113412,
    equipTau: 3,
    utilW: 0,
    utilTau: 4.60174,
    possW: 0.117807,
    centroidW: -0.39709,
    nearestW: 0.382335,
    timeW: 1.876547,
    timePow: 6.615961,
    plantW: -1.272248,
    bombW: -0.646404,
    bombPow: 0.4,
    kitW: 1.803375,
    noDefuseW: -2.245362,
    bombDistW: 2,
    bombDuelW: 0,
    defuseSlackW: 1.170859,
    defuseSlackTau: 3.073271,
    defuseImpossibleW: 0,
    siteOccW: 0.135454,
    keyZoneW: 0.308123,
    approachDistW: 0.875852
  }
};

let cached = null;

// Weights fitted on the server against the whole replay library beat the ones
// compiled into this bundle, which were fitted on a sample. The fetch is
// started once, and the cached vector is dropped when better weights land so
// the next prediction picks them up. Until then, and on any failure, the values
// below are used unchanged.
primeRuntimeParams('round', ROUND_MODEL_PARAMS.specHash, () => {
  cached = null;
});

/** The fitted parameter vector, in roundParamSpec order. */
export function roundParamVector() {
  if (!cached) {
    const live = runtimeParams('round');
    const useLive = live && live.specHash === ROUND_MODEL_PARAMS.specHash;
    cached = fromNamed(useLive ? live.values : ROUND_MODEL_PARAMS.values);
  }
  return cached;
}

/** The fitted per-phase output curve, for predictRoundCalibrated. */
export function roundCalibration() {
  return ROUND_MODEL_PARAMS.calibration;
}
