// ---------------------------------------------------------------------------
// replays/rounds/roundModelParams.js
// GENERATED by scripts/train-round-model.mjs. Do not edit by hand.
//
// Fitted against 612 rounds from the parsed demos in sampledemos/.
// Validation is held out by demo, so no round contributes to both halves.
//
//   validation log loss  0.4407   (a coin flip scores 0.6931)
//   validation brier     0.1474
//   training log loss    0.4033
//
// The three exams, on held-out demos:
//   early to mid    loss 0.5092
//   mid to late     loss 0.3921
//   10s before end  loss 0.2021
//
// To refit:
//   node scripts/fetch-zone-networks.mjs
//   node scripts/extract-round-snapshots.mjs
//   node scripts/train-round-model.mjs --generations 60 --export
// ---------------------------------------------------------------------------

import { fromNamed } from './roundParamSpec.js';

export const ROUND_MODEL_PARAMS = {
  specHash: 'd06895c',
  trainedOn: 612,
  validation: {
    logLoss: 0.4407,
    brier: 0.147413,
    exam: 4.3177
  },
  exams: {
    early: { logLoss: 0.509202, exam: 3.5928, n: 128 },
    mid: { logLoss: 0.392097, exam: 5.0358, n: 109 },
    final: { logLoss: 0.202125, exam: 7.3548, n: 123 }
  },
  values: {
    bias: 0.168492,
    map_ANC: -0.420098,
    map_ANU: -0.433193,
    map_CCH: 0.713495,
    map_DD2: -0.152771,
    map_INF: 0.202347,
    map_MIR: -0.101797,
    manW: 5.805651,
    manTau: 3.64722,
    hpW: 2.48812,
    lastManW: 1.16293,
    duelW: 1.763653,
    duelTau: 9.085833,
    equipW: 4.460557,
    equipTau: 1.845074,
    utilW: 0,
    utilTau: 2.18773,
    possW: 0.151517,
    centroidW: -0.168323,
    nearestW: 0.473546,
    timeW: 0.850947,
    timePow: 12,
    plantW: -1.462857,
    bombW: -2.245929,
    bombPow: 2.635441,
    kitW: 1.561213,
    noDefuseW: -0.423202
  }
};

let cached = null;

/** The fitted parameter vector, in roundParamSpec order. */
export function roundParamVector() {
  if (!cached) cached = fromNamed(ROUND_MODEL_PARAMS.values);
  return cached;
}
