// ---------------------------------------------------------------------------
// shared/sim3d/surfaces.js
// GENERATED by scripts/cs3d-surfaces.mjs — do not edit by hand.
//
// The game's own surface table, merged out of
// surfaceproperties/surfaceproperties.vsurf and
// scripts/surfaceproperties_game.txt with the `base` chains resolved, so every
// row below is complete rather than a diff against its parent.
//
// Fields, and who reads them:
//
//   material     [docs] the one-letter game material. 'G' grate, 'Y' glass,
//                'M' solid metal, 'C' concrete, ... CS special-cases the first
//                two when a bullet hits them (shared/sim3d/penetration.js).
//   penetration  [docs] bulletPenetrationDistanceModifier — how much of a
//                bullet's penetration budget this surface costs. Higher is
//                easier to shoot through: metalgrate 0.95, solidmetal 0.27.
//   damage       [docs] bulletPenetrationDamageModifier — the share of damage
//                that survives the wall.
//   climbable    [docs] whether a player can climb it. This is the ladder flag
//                (shared/sim3d/motion.js).
//   jump/speed   [docs] jumpfactor / maxspeedfactor.
//   smoke        [docs] allowsmokethrough.
//   density/elasticity/friction/thickness  [docs] the physics block. Nothing
//                reads these yet — a grenade's bounce comes from its own
//                m_flElasticity, measured in shared/sim3d/grenade.js.
//
// A map's collision carries a surface name per triangle (mapLoader's
// `collider.surfaceOf`), which is the key into this table.
// ---------------------------------------------------------------------------

/** 164 surfaces, keyed by their lower-cased name. */
export const SURFACES = Object.freeze({
  "alienflesh": { material: "H", penetration: 0.9, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "armorflesh": { material: "M", penetration: 0.5, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "asphalt": { material: "Q", penetration: 0.55, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "audioblocker": { material: "X", penetration: 0.5, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 0, elasticity: 0, friction: 0, thickness: -1 },
  "audioblocker_inneredge": { material: "X", penetration: 0.5, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 0, elasticity: 0, friction: 0, thickness: -1 },
  "audioblocker_middleedge": { material: "X", penetration: 0.5, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 0, elasticity: 0, friction: 0, thickness: -1 },
  "audioblocker_outeredge": { material: "X", penetration: 0.5, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 0, elasticity: 0, friction: 0, thickness: -1 },
  "balloon": { material: "C", penetration: 0.5, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "beans": { material: "11", penetration: 0.6, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "blockbullets": { material: "X", penetration: 0.01, damage: 0.001, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 1 },
  "bloodyflesh": { material: "B", penetration: 0.9, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "boulder": { material: "3", penetration: 0.5, damage: 0.25, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "brakingrubbertire": { material: "4", penetration: 0.85, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.6, thickness: -1 },
  "brass_bell_large": { material: "", penetration: 0.5, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "brass_bell_medium": { material: "", penetration: 0.5, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "brass_bell_small": { material: "", penetration: 0.5, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "brass_bell_smallest": { material: "", penetration: 0.5, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "brass_bell_smallest_g": { material: "", penetration: 0.5, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "brick": { material: "R", penetration: 0.47, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "canister": { material: "V", penetration: 0.5, damage: 0.45, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.1 },
  "cardboard": { material: "U", penetration: 0.95, damage: 0.99, climbable: false, jump: 1, speed: 1, smoke: false, density: 500, elasticity: 0.25, friction: 0.8, thickness: 0.25 },
  "cardboard_smallbox": { material: "U", penetration: 0.95, damage: 0.99, climbable: false, jump: 1, speed: 1, smoke: false, density: 500, elasticity: 0.25, friction: 0.8, thickness: 0.25 },
  "carpet": { material: "7", penetration: 0.75, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 500, elasticity: 0.01, friction: 0.8, thickness: 0.1 },
  "ceiling_tile": { material: "U", penetration: 0.95, damage: 0.99, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.25 },
  "chain": { material: "G", penetration: 0.99, damage: 0.99, climbable: false, jump: 1, speed: 1, smoke: true, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.5 },
  "chainlink": { material: "G", penetration: 0.99, damage: 0.99, climbable: false, jump: 1, speed: 1, smoke: true, density: 1600, elasticity: 0.25, friction: 0.8, thickness: 0.5 },
  "clay": { material: "1", penetration: 0.95, damage: 0.6, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.5 },
  "cloth": { material: "7", penetration: 0.75, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 500, elasticity: 0.01, friction: 0.8, thickness: 0.1 },
  "computer": { material: "P", penetration: 0.4, damage: 0.45, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.1 },
  "concrete": { material: "C", penetration: 0.5, damage: 0.25, climbable: false, jump: 1, speed: 1, smoke: false, density: 2400, elasticity: 0.2, friction: 0.8, thickness: -1 },
  "concrete_block": { material: "C", penetration: 0.5, damage: 0.25, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "concrete_polished": { material: "C", penetration: 0.5, damage: 0.25, climbable: false, jump: 1, speed: 1, smoke: false, density: 2400, elasticity: 0.2, friction: 0.8, thickness: -1 },
  "default": { material: "C", penetration: 0.5, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "default_silent": { material: "X", penetration: 0.5, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "defuser": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.95, friction: 0.8, thickness: 0.1 },
  "dirt": { material: "D", penetration: 0.6, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 1600, elasticity: 0.01, friction: 0.8, thickness: -1 },
  "dufflebag_survivalcase": { material: "7", penetration: 0.75, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.1 },
  "flesh": { material: "F", penetration: 0.9, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 900, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "floating_metal_barrel": { material: "12", penetration: 0.01, damage: 0.01, climbable: false, jump: 1, speed: 1, smoke: false, density: 500, elasticity: 0.25, friction: 0.8, thickness: 0.1 },
  "floatingstandable": { material: "D", penetration: 0.6, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 800, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "foliage": { material: "O", penetration: 0.95, damage: 0.6, climbable: false, jump: 1, speed: 1, smoke: false, density: 700, elasticity: 0.1, friction: 0.8, thickness: -1 },
  "fruit": { material: "F", penetration: 0.9, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 900, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "glass": { material: "Y", penetration: 0.99, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2700, elasticity: 0.2, friction: 0.5, thickness: 0.5 },
  "glassbottle": { material: "Y", penetration: 0.99, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.3, friction: 0.4, thickness: 0.5 },
  "glassfloor": { material: "Y", penetration: 0.99, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2700, elasticity: 0.2, friction: 0.8, thickness: 0.5 },
  "grass": { material: "J", penetration: 0.6, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "grate": { material: "G", penetration: 0.95, damage: 0.99, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.5 },
  "gravel": { material: "3", penetration: 0.4, damage: 0.25, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "grenade": { material: "V", penetration: 0.5, damage: 0.45, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.01, friction: 0.9, thickness: 0.1 },
  "ice": { material: "", penetration: 0.75, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 917, elasticity: 0.1, friction: 0.1, thickness: -1 },
  "item": { material: "L", penetration: 0.75, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 600, elasticity: 0.25, friction: 0.8, thickness: 0.25 },
  "jalopy": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.1 },
  "jalopytire": { material: "4", penetration: 0.85, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.1, friction: 0.8, thickness: -1 },
  "jeeptire": { material: "4", penetration: 0.85, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 1.337, thickness: -1 },
  "ladder": { material: "X", penetration: 0.4, damage: 0.3, climbable: true, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.1 },
  "metal": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.1 },
  "metal_barrel": { material: "12", penetration: 0.01, damage: 0.01, climbable: false, jump: 1, speed: 1, smoke: false, density: 2700, elasticity: 0.1, friction: 0.8, thickness: 0.1 },
  "metal_barrel_explodingsurvival": { material: "12", penetration: 0.01, damage: 0.01, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.1 },
  "metal_barrelsoundoverride": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.1 },
  "metal_bouncy": { material: "M", penetration: 0.27, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 10000, elasticity: 1000, friction: 0, thickness: -1 },
  "metal_box": { material: "M", penetration: 0.5, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.1 },
  "metal_dumpster": { material: "12", penetration: 0.01, damage: 0.01, climbable: false, jump: 1, speed: 1, smoke: false, density: 2700, elasticity: 0.1, friction: 0.8, thickness: 0.1 },
  "metal_sand_barrel": { material: "12", penetration: 0.01, damage: 0.01, climbable: false, jump: 1, speed: 1, smoke: false, density: 2700, elasticity: 0.1, friction: 0.8, thickness: -1 },
  "metal_sheet_corrugated": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.1 },
  "metal_sheetmetal": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.1 },
  "metal_shield": { material: "14", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.1 },
  "metal_survivalcase": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.1 },
  "metal_survivalcase_unpunchable": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.1 },
  "metal_vehiclesoundoverride": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.1 },
  "metal_ventslat": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.1 },
  "metaldogtags": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.1 },
  "metalgrate": { material: "G", penetration: 0.95, damage: 0.99, climbable: false, jump: 1, speed: 1, smoke: false, density: 1600, elasticity: 0.25, friction: 0.8, thickness: 0.5 },
  "metalpanel": { material: "V", penetration: 0.5, damage: 0.45, climbable: false, jump: 1, speed: 1, smoke: false, density: 2700, elasticity: 0.2, friction: 0.8, thickness: 0.1 },
  "metalrailing": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: true, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.1 },
  "metalvehicle": { material: "M", penetration: 0.5, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2700, elasticity: 0.2, friction: 0.8, thickness: 0.1 },
  "metalvent": { material: "V", penetration: 0.6, damage: 0.45, climbable: false, jump: 1, speed: 1, smoke: false, density: 2700, elasticity: 0.1, friction: 0.8, thickness: 0.04 },
  "mud": { material: "11", penetration: 0.6, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "no_decal": { material: "-", penetration: 0.5, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 900, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "paintcan": { material: "M", penetration: 0.5, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.99, friction: 0.3, thickness: 0.1 },
  "paper": { material: "U", penetration: 0.95, damage: 0.99, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.25 },
  "papercup": { material: "U", penetration: 0.95, damage: 0.99, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.1, friction: 0.8, thickness: 0.25 },
  "papertowel": { material: "U", penetration: 0.95, damage: 0.99, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.25 },
  "plaster": { material: "2", penetration: 0.7, damage: 0.6, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "plaster_drywall": { material: "2", penetration: 0.7, damage: 0.6, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "plastic": { material: "L", penetration: 0.75, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.25 },
  "plastic_autocover": { material: "L", penetration: 0.75, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.25 },
  "plastic_barrel": { material: "L", penetration: 0.7, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 500, elasticity: 0.01, friction: 0.8, thickness: 0.25 },
  "plastic_barrel_buoyant": { material: "L", penetration: 0.7, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 150, elasticity: 0.25, friction: 0.8, thickness: 0.25 },
  "plastic_box": { material: "L", penetration: 0.75, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 500, elasticity: 0.01, friction: 0.8, thickness: 0.25 },
  "plastic_dumpster": { material: "L", penetration: 0.75, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 500, elasticity: 0.01, friction: 0.8, thickness: 0.25 },
  "plastic_milkcrate": { material: "L", penetration: 0.75, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.25 },
  "plastic_solid": { material: "L", penetration: 0, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.25 },
  "plastic_survivalcase": { material: "L", penetration: 0.75, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.25 },
  "plastic_tape": { material: "L", penetration: 0.75, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.25 },
  "plasticbottle": { material: "L", penetration: 0.75, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.25 },
  "player": { material: "", penetration: 0.5, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 1000, elasticity: 0.001, friction: 0.5, thickness: -1 },
  "player_control_clip": { material: "I", penetration: 0.5, damage: 1, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "playerflesh": { material: "F", penetration: 0.9, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 900, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "popcan": { material: "M", penetration: 0.5, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.99, friction: 0.3, thickness: 0.1 },
  "porcelain": { material: "3", penetration: 0.95, damage: 0.25, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "pottery": { material: "1", penetration: 0.95, damage: 0.6, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.3, friction: 0.4, thickness: 0.5 },
  "potterylarge": { material: "1", penetration: 0.95, damage: 0.6, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.3, friction: 0.4, thickness: 0.5 },
  "puddle": { material: "10", penetration: 0.5, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "quicksand": { material: "", penetration: 0.2, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 600, elasticity: 2, friction: 0.8, thickness: -1 },
  "rock": { material: "3", penetration: 0.5, damage: 0.25, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "roller": { material: "V", penetration: 0.5, damage: 0.45, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.3, friction: 0.7, thickness: 0.1 },
  "rubber": { material: "4", penetration: 0.85, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.2, friction: 0.8, thickness: -1 },
  "rubbertire": { material: "4", penetration: 0.85, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 1, thickness: -1 },
  "sand": { material: "N", penetration: 0.3, damage: 0.25, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "sheetrock": { material: "5", penetration: 0.85, damage: 0.6, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "slidingrubbertire": { material: "4", penetration: 0.85, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.2, thickness: -1 },
  "slidingrubbertire_front": { material: "4", penetration: 0.85, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.2, thickness: -1 },
  "slidingrubbertire_jalopyfront": { material: "4", penetration: 0.85, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.15, thickness: -1 },
  "slidingrubbertire_jalopyrear": { material: "4", penetration: 0.85, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.15, thickness: -1 },
  "slidingrubbertire_rear": { material: "4", penetration: 0.85, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.2, thickness: -1 },
  "slime": { material: "S", penetration: 0.5, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.1, friction: 0.9, thickness: -1 },
  "slipperymetal": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.15, friction: 0.1, thickness: 0.1 },
  "slipperyslide": { material: "M", penetration: 0.27, damage: 0.3, climbable: false, jump: 0.7, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.1, thickness: -1 },
  "slipperyslime": { material: "D", penetration: 0.6, damage: 0.3, climbable: false, jump: 0.7, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.1, thickness: -1 },
  "slowgrass": { material: "J", penetration: 0.6, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "snow": { material: "K", penetration: 0.85, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "soccerball": { material: "-", penetration: 0.5, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 900, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "solidmetal": { material: "M", penetration: 0.27, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2700, elasticity: 0.1, friction: 0.8, thickness: -1 },
  "strongman_bell": { material: "M", penetration: 0.27, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "stucco": { material: "2", penetration: 0.5, damage: 0.25, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "sugarcane": { material: "J", penetration: 0.6, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "tile": { material: "T", penetration: 0.7, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2700, elasticity: 0.3, friction: 0.8, thickness: 0.5 },
  "tile_survivalcase": { material: "T", penetration: 0.7, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.5 },
  "tile_survivalcase_gib": { material: "T", penetration: 0.7, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.5 },
  "upholstery": { material: "9", penetration: 0.75, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 500, elasticity: 0.01, friction: 0.8, thickness: 0.1 },
  "wade": { material: "X", penetration: 0.3, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "water": { material: "S", penetration: 0.3, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 1000, elasticity: 0.1, friction: 0.8, thickness: -1 },
  "watermelon": { material: "S", penetration: 0.95, damage: 0.6, climbable: false, jump: 1, speed: 1, smoke: false, density: 900, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "weapon": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.95, friction: 0.8, thickness: 0.1 },
  "weapon_magazine": { material: "M", penetration: 0.4, damage: 0.45, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 0.1 },
  "weaponc4": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 900, elasticity: 0.95, friction: 0.8, thickness: 0.1 },
  "weaponflashbang": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.95, friction: 0.8, thickness: 0.1 },
  "weaponheavy": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.95, friction: 0.8, thickness: 0.1 },
  "weaponhegrenade": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.95, friction: 0.8, thickness: 0.1 },
  "weaponincendiary": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.95, friction: 0.8, thickness: 0.1 },
  "weaponknife": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.95, friction: 0.8, thickness: 0.1 },
  "weaponmagazine": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.95, friction: 0.8, thickness: 0.1 },
  "weaponmolotov": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.95, friction: 0.8, thickness: 0.1 },
  "weaponpistol": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.95, friction: 0.8, thickness: 0.1 },
  "weaponrifle": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.95, friction: 0.8, thickness: 0.1 },
  "weaponshotgun": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.95, friction: 0.8, thickness: 0.1 },
  "weaponsmg": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.95, friction: 0.8, thickness: 0.1 },
  "weaponsniper": { material: "M", penetration: 0.4, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.95, friction: 0.8, thickness: 0.1 },
  "wet": { material: "S", penetration: 0.5, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "wet_concrete": { material: "S", penetration: 0.5, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "wet_mud": { material: "S", penetration: 0.5, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "wet_sand": { material: "S", penetration: 0.5, damage: 0.5, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "wood": { material: "W", penetration: 0.9, damage: 0.6, climbable: false, jump: 1, speed: 1, smoke: false, density: 700, elasticity: 0.1, friction: 0.8, thickness: -1 },
  "wood_basket": { material: "W", penetration: 0.9, damage: 0.6, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "wood_box": { material: "W", penetration: 0.9, damage: 0.6, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "wood_crate": { material: "W", penetration: 0.9, damage: 0.6, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "wood_dense": { material: "13", penetration: 0.5, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2700, elasticity: 0.25, friction: 0.8, thickness: 0.1 },
  "wood_furniture": { material: "W", penetration: 0.9, damage: 0.6, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "wood_ladder": { material: "X", penetration: 0.9, damage: 0.6, climbable: true, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "wood_lowdensity": { material: "W", penetration: 0.9, damage: 0.6, climbable: false, jump: 1, speed: 1, smoke: false, density: 300, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "wood_panel": { material: "W", penetration: 0.9, damage: 0.6, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: 1 },
  "wood_plank": { material: "W", penetration: 0.85, damage: 0.6, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "wood_solid": { material: "W", penetration: 0.8, damage: 0.6, climbable: false, jump: 1, speed: 1, smoke: false, density: 2000, elasticity: 0.25, friction: 0.8, thickness: -1 },
  "wood_tree": { material: "13", penetration: 0.5, damage: 0.3, climbable: false, jump: 1, speed: 1, smoke: false, density: 2700, elasticity: 0.25, friction: 0.8, thickness: 0.1 }
});

/** What an unknown surface behaves like. */
export const DEFAULT_SURFACE = SURFACES.default;

/** Look one up, never null. */
export function surface(name) {
  return SURFACES[String(name || '').toLowerCase()] || DEFAULT_SURFACE;
}

/** [docs] Game materials CS treats as see-through-and-shoot-through. */
export const MAT_GRATE = 'G';
export const MAT_GLASS = 'Y';
export const MAT_METAL = 'M';

/** The 2 surfaces the game marks climbable. */
export const CLIMBABLE = Object.freeze(["ladder", "wood_ladder"]);
