-- ===========================================================================
-- 0003_seed_plans.sql
--
-- GENERATED FILE. Do not edit by hand.
-- Source: shared/entitlements/catalogue.js
-- Regenerate: node scripts/sync-plan-capabilities.mjs
--
-- Prices stay null until a billing provider is wired up. The pricing page reads
-- them from here, so a null price renders as "not for sale yet" rather than as
-- a broken checkout button.
-- ===========================================================================

insert into public.plans (id, name, rank, seat_capacity, team_capacity, capabilities)
values
  ('free', 'Free', 0,
   0, 0,
   '{
      "demos.ads_free": false,
      "demos.full_recent_access": false,
      "demos.viewer": true,
      "demos.macro_viewer": 1,
      "demos.upload_limit": 3,
      "demos.map_control": 0,
      "demos.round_win_prediction": 0,
      "demos.duel_win_prediction": 0,
      "demos.auto_coach": 1,
      "demos.teamspeak_sync": false,
      "demos.comms_coach": false,
      "drawing_board": "none",
      "stats.single_game": false,
      "stats.team_statistics": false,
      "stats.metrics_player_full": false,
      "stats.metrics_team_full": false,
      "stats.filters_full": false,
      "analytics.charts": 3,
      "analytics.pattern_finder": 3,
      "team.create_limit": 0,
      "team.join": false,
      "team.seat_capacity": 0,
      "team.documents": 0,
      "team.roles_positions": false,
      "team.stratbook_access": false,
      "team.stratbook_limit": 0,
      "team.utility_archive": 0,
      "team.strategy_creator_2d": 0,
      "team.auto_round_winrates": false,
      "aim.trainer": true,
      "aim.routines": true,
      "aim.advanced_analytics": false,
      "aim.replays": "none",
      "aim.custom_routines": 0,
      "aim.cosmetics": "none"
    }'::jsonb),
  ('premium', 'Premium', 10,
   1, 0,
   '{
      "demos.ads_free": true,
      "demos.full_recent_access": true,
      "demos.viewer": true,
      "demos.macro_viewer": -1,
      "demos.upload_limit": 50,
      "demos.map_control": 0,
      "demos.round_win_prediction": 0,
      "demos.duel_win_prediction": 0,
      "demos.auto_coach": 4,
      "demos.teamspeak_sync": false,
      "demos.comms_coach": false,
      "drawing_board": "nosave",
      "stats.single_game": false,
      "stats.team_statistics": false,
      "stats.metrics_player_full": true,
      "stats.metrics_team_full": false,
      "stats.filters_full": true,
      "analytics.charts": -1,
      "analytics.pattern_finder": -1,
      "team.create_limit": 0,
      "team.join": true,
      "team.seat_capacity": 1,
      "team.documents": 10,
      "team.roles_positions": true,
      "team.stratbook_access": true,
      "team.stratbook_limit": 40,
      "team.utility_archive": 50,
      "team.strategy_creator_2d": 2,
      "team.auto_round_winrates": false,
      "aim.trainer": true,
      "aim.routines": true,
      "aim.advanced_analytics": true,
      "aim.replays": "best_and_recent",
      "aim.custom_routines": 3,
      "aim.cosmetics": "presets"
    }'::jsonb),
  ('team_premium', 'Team Premium', 20,
   7, 1,
   '{
      "demos.ads_free": true,
      "demos.full_recent_access": true,
      "demos.viewer": true,
      "demos.macro_viewer": -1,
      "demos.upload_limit": -1,
      "demos.map_control": 1,
      "demos.round_win_prediction": 1,
      "demos.duel_win_prediction": 1,
      "demos.auto_coach": -1,
      "demos.teamspeak_sync": false,
      "demos.comms_coach": false,
      "drawing_board": "limited",
      "stats.single_game": true,
      "stats.team_statistics": true,
      "stats.metrics_player_full": true,
      "stats.metrics_team_full": false,
      "stats.filters_full": true,
      "analytics.charts": -1,
      "analytics.pattern_finder": -1,
      "team.create_limit": 1,
      "team.join": true,
      "team.seat_capacity": 7,
      "team.documents": 10,
      "team.roles_positions": true,
      "team.stratbook_access": true,
      "team.stratbook_limit": 40,
      "team.utility_archive": 50,
      "team.strategy_creator_2d": 2,
      "team.auto_round_winrates": false,
      "aim.trainer": true,
      "aim.routines": true,
      "aim.advanced_analytics": true,
      "aim.replays": "best_plus_10",
      "aim.custom_routines": 10,
      "aim.cosmetics": "presets"
    }'::jsonb),
  ('team_elite', 'Team Elite', 30,
   14, 2,
   '{
      "demos.ads_free": true,
      "demos.full_recent_access": true,
      "demos.viewer": true,
      "demos.macro_viewer": -1,
      "demos.upload_limit": -1,
      "demos.map_control": -1,
      "demos.round_win_prediction": -1,
      "demos.duel_win_prediction": -1,
      "demos.auto_coach": -1,
      "demos.teamspeak_sync": true,
      "demos.comms_coach": true,
      "drawing_board": "full",
      "stats.single_game": true,
      "stats.team_statistics": true,
      "stats.metrics_player_full": true,
      "stats.metrics_team_full": true,
      "stats.filters_full": true,
      "analytics.charts": -1,
      "analytics.pattern_finder": -1,
      "team.create_limit": 2,
      "team.join": true,
      "team.seat_capacity": 14,
      "team.documents": -1,
      "team.roles_positions": true,
      "team.stratbook_access": true,
      "team.stratbook_limit": -1,
      "team.utility_archive": -1,
      "team.strategy_creator_2d": -1,
      "team.auto_round_winrates": true,
      "aim.trainer": true,
      "aim.routines": true,
      "aim.advanced_analytics": true,
      "aim.replays": "full",
      "aim.custom_routines": -1,
      "aim.cosmetics": "full"
    }'::jsonb)
on conflict (id) do update set
  name          = excluded.name,
  rank          = excluded.rank,
  seat_capacity = excluded.seat_capacity,
  team_capacity = excluded.team_capacity,
  capabilities  = excluded.capabilities;
