-- ===========================================================================
-- 0003_seed_plans.sql
--
-- GENERATED FILE. Do not edit by hand.
-- Source: shared/entitlements/catalogue.js
-- Regenerate: node scripts/sync-plan-capabilities.mjs
--
-- Prices are the TOTAL charged for one term, in cents, with both the term
-- discount and the per-plan long-term bonus already applied. Enforcement never
-- reads them; they are here so SQL reporting and a future provider price sync
-- share one source with the pricing page.
-- ===========================================================================

-- The six-month term postdates 0002, and this file runs before the migration
-- that adds it on a fresh project. Idempotent, so re-running is free.
alter table public.plans add column if not exists price_halfyear_cents int;

insert into public.plans (
  id, name, rank, seat_capacity, team_capacity,
  price_month_cents, price_quarter_cents, price_halfyear_cents, price_year_cents,
  capabilities
)
values
  ('free', 'Free', 0,
   0, 0,
   0, 0,
   0, 0,
   '{
      "demos.viewer": true,
      "demos.ads_free": false,
      "demos.full_recent_access": false,
      "demos.macro_viewer": 1,
      "demos.upload_limit": 3,
      "demos.map_control": 0,
      "demos.round_win_prediction": 0,
      "demos.duel_win_prediction": 0,
      "demos.auto_coach": 0,
      "demos.teamspeak_sync": false,
      "demos.comms_coach": 0,
      "drawing_board": "none",
      "stats.performance_chapters": false,
      "stats.single_game": false,
      "stats.team_statistics": false,
      "stats.metrics_player_full": false,
      "stats.metrics_team_full": false,
      "stats.filters_full": false,
      "analytics.charts": 3,
      "analytics.pattern_finder": 3,
      "analytics.antistrat": 0,
      "team.create_limit": 0,
      "team.join": false,
      "team.seat_capacity": 0,
      "team.documents": 0,
      "team.roles_positions": false,
      "team.playlists": false,
      "team.comms": false,
      "team.stratbook_access": false,
      "team.stratbook_limit": 0,
      "team.utility_archive": 0,
      "team.strategy_creator_2d": 0,
      "team.auto_round_winrates": false,
      "aim.trainer": true,
      "aim.routines": true,
      "aim.map_practice": false,
      "aim.advanced_analytics": false,
      "aim.replays": "none",
      "aim.custom_routines": 0,
      "aim.cosmetics": "none"
    }'::jsonb),
  ('solo_lite', 'Solo Lite', 10,
   0, 0,
   899, 2481,
   4693, 8630,
   '{
      "demos.viewer": true,
      "demos.ads_free": true,
      "demos.full_recent_access": true,
      "demos.macro_viewer": -1,
      "demos.upload_limit": 100,
      "demos.map_control": 1,
      "demos.round_win_prediction": 1,
      "demos.duel_win_prediction": 1,
      "demos.auto_coach": 1,
      "demos.teamspeak_sync": false,
      "demos.comms_coach": 0,
      "drawing_board": "nosave",
      "stats.performance_chapters": true,
      "stats.single_game": true,
      "stats.team_statistics": true,
      "stats.metrics_player_full": true,
      "stats.metrics_team_full": false,
      "stats.filters_full": true,
      "analytics.charts": -1,
      "analytics.pattern_finder": -1,
      "analytics.antistrat": 0,
      "team.create_limit": 0,
      "team.join": true,
      "team.seat_capacity": 0,
      "team.documents": 0,
      "team.roles_positions": false,
      "team.playlists": false,
      "team.comms": false,
      "team.stratbook_access": false,
      "team.stratbook_limit": 0,
      "team.utility_archive": 0,
      "team.strategy_creator_2d": 0,
      "team.auto_round_winrates": false,
      "aim.trainer": true,
      "aim.routines": true,
      "aim.map_practice": true,
      "aim.advanced_analytics": true,
      "aim.replays": "best_and_recent",
      "aim.custom_routines": 5,
      "aim.cosmetics": "presets"
    }'::jsonb),
  ('solo_premium', 'Solo Premium', 20,
   0, 0,
   2499, 6690,
   12523, 22791,
   '{
      "demos.viewer": true,
      "demos.ads_free": true,
      "demos.full_recent_access": true,
      "demos.macro_viewer": -1,
      "demos.upload_limit": 300,
      "demos.map_control": 3,
      "demos.round_win_prediction": 3,
      "demos.duel_win_prediction": 3,
      "demos.auto_coach": 3,
      "demos.teamspeak_sync": false,
      "demos.comms_coach": 0,
      "drawing_board": "limited",
      "stats.performance_chapters": true,
      "stats.single_game": true,
      "stats.team_statistics": true,
      "stats.metrics_player_full": true,
      "stats.metrics_team_full": true,
      "stats.filters_full": true,
      "analytics.charts": -1,
      "analytics.pattern_finder": -1,
      "analytics.antistrat": 0,
      "team.create_limit": 0,
      "team.join": true,
      "team.seat_capacity": 0,
      "team.documents": 0,
      "team.roles_positions": false,
      "team.playlists": false,
      "team.comms": false,
      "team.stratbook_access": false,
      "team.stratbook_limit": 0,
      "team.utility_archive": 0,
      "team.strategy_creator_2d": 0,
      "team.auto_round_winrates": false,
      "aim.trainer": true,
      "aim.routines": true,
      "aim.map_practice": true,
      "aim.advanced_analytics": true,
      "aim.replays": "best_plus_10",
      "aim.custom_routines": 15,
      "aim.cosmetics": "presets"
    }'::jsonb),
  ('solo_elite', 'Solo Elite', 30,
   0, 0,
   6999, 18351,
   34343, 62487,
   '{
      "demos.viewer": true,
      "demos.ads_free": true,
      "demos.full_recent_access": true,
      "demos.macro_viewer": -1,
      "demos.upload_limit": -1,
      "demos.map_control": -1,
      "demos.round_win_prediction": -1,
      "demos.duel_win_prediction": -1,
      "demos.auto_coach": -1,
      "demos.teamspeak_sync": false,
      "demos.comms_coach": 0,
      "drawing_board": "full",
      "stats.performance_chapters": true,
      "stats.single_game": true,
      "stats.team_statistics": true,
      "stats.metrics_player_full": true,
      "stats.metrics_team_full": true,
      "stats.filters_full": true,
      "analytics.charts": -1,
      "analytics.pattern_finder": -1,
      "analytics.antistrat": 0,
      "team.create_limit": 0,
      "team.join": true,
      "team.seat_capacity": 0,
      "team.documents": 0,
      "team.roles_positions": false,
      "team.playlists": false,
      "team.comms": false,
      "team.stratbook_access": false,
      "team.stratbook_limit": 0,
      "team.utility_archive": 0,
      "team.strategy_creator_2d": 0,
      "team.auto_round_winrates": false,
      "aim.trainer": true,
      "aim.routines": true,
      "aim.map_practice": true,
      "aim.advanced_analytics": true,
      "aim.replays": "full",
      "aim.custom_routines": -1,
      "aim.cosmetics": "full"
    }'::jsonb),
  ('team_tier3', 'Team Tier 3', 40,
   7, 1,
   8999, 24092,
   45096, 82071,
   '{
      "demos.viewer": true,
      "demos.ads_free": true,
      "demos.full_recent_access": true,
      "demos.macro_viewer": -1,
      "demos.upload_limit": 400,
      "demos.map_control": 1,
      "demos.round_win_prediction": 1,
      "demos.duel_win_prediction": 1,
      "demos.auto_coach": 1,
      "demos.teamspeak_sync": true,
      "demos.comms_coach": 1,
      "drawing_board": "limited",
      "stats.performance_chapters": true,
      "stats.single_game": true,
      "stats.team_statistics": true,
      "stats.metrics_player_full": true,
      "stats.metrics_team_full": false,
      "stats.filters_full": true,
      "analytics.charts": -1,
      "analytics.pattern_finder": -1,
      "analytics.antistrat": 1,
      "team.create_limit": 1,
      "team.join": true,
      "team.seat_capacity": 7,
      "team.documents": 10,
      "team.roles_positions": true,
      "team.playlists": true,
      "team.comms": true,
      "team.stratbook_access": true,
      "team.stratbook_limit": 40,
      "team.utility_archive": 50,
      "team.strategy_creator_2d": 3,
      "team.auto_round_winrates": false,
      "aim.trainer": true,
      "aim.routines": true,
      "aim.map_practice": true,
      "aim.advanced_analytics": true,
      "aim.replays": "best_and_recent",
      "aim.custom_routines": 5,
      "aim.cosmetics": "presets"
    }'::jsonb),
  ('team_tier2', 'Team Tier 2', 50,
   14, 2,
   24999, 65547,
   122665, 223191,
   '{
      "demos.viewer": true,
      "demos.ads_free": true,
      "demos.full_recent_access": true,
      "demos.macro_viewer": -1,
      "demos.upload_limit": -1,
      "demos.map_control": 3,
      "demos.round_win_prediction": 3,
      "demos.duel_win_prediction": 3,
      "demos.auto_coach": 3,
      "demos.teamspeak_sync": true,
      "demos.comms_coach": 3,
      "drawing_board": "full",
      "stats.performance_chapters": true,
      "stats.single_game": true,
      "stats.team_statistics": true,
      "stats.metrics_player_full": true,
      "stats.metrics_team_full": true,
      "stats.filters_full": true,
      "analytics.charts": -1,
      "analytics.pattern_finder": -1,
      "analytics.antistrat": 3,
      "team.create_limit": 2,
      "team.join": true,
      "team.seat_capacity": 14,
      "team.documents": 30,
      "team.roles_positions": true,
      "team.playlists": true,
      "team.comms": true,
      "team.stratbook_access": true,
      "team.stratbook_limit": 120,
      "team.utility_archive": 150,
      "team.strategy_creator_2d": 9,
      "team.auto_round_winrates": true,
      "aim.trainer": true,
      "aim.routines": true,
      "aim.map_practice": true,
      "aim.advanced_analytics": true,
      "aim.replays": "best_plus_10",
      "aim.custom_routines": 15,
      "aim.cosmetics": "presets"
    }'::jsonb),
  ('team_tier1', 'Team Tier 1', 60,
   20, 3,
   69999, 177741,
   332509, 604791,
   '{
      "demos.viewer": true,
      "demos.ads_free": true,
      "demos.full_recent_access": true,
      "demos.macro_viewer": -1,
      "demos.upload_limit": -1,
      "demos.map_control": -1,
      "demos.round_win_prediction": -1,
      "demos.duel_win_prediction": -1,
      "demos.auto_coach": -1,
      "demos.teamspeak_sync": true,
      "demos.comms_coach": -1,
      "drawing_board": "full",
      "stats.performance_chapters": true,
      "stats.single_game": true,
      "stats.team_statistics": true,
      "stats.metrics_player_full": true,
      "stats.metrics_team_full": true,
      "stats.filters_full": true,
      "analytics.charts": -1,
      "analytics.pattern_finder": -1,
      "analytics.antistrat": -1,
      "team.create_limit": 3,
      "team.join": true,
      "team.seat_capacity": 20,
      "team.documents": -1,
      "team.roles_positions": true,
      "team.playlists": true,
      "team.comms": true,
      "team.stratbook_access": true,
      "team.stratbook_limit": -1,
      "team.utility_archive": -1,
      "team.strategy_creator_2d": -1,
      "team.auto_round_winrates": true,
      "aim.trainer": true,
      "aim.routines": true,
      "aim.map_practice": true,
      "aim.advanced_analytics": true,
      "aim.replays": "full",
      "aim.custom_routines": -1,
      "aim.cosmetics": "full"
    }'::jsonb)
on conflict (id) do update set
  name                 = excluded.name,
  rank                 = excluded.rank,
  seat_capacity        = excluded.seat_capacity,
  team_capacity        = excluded.team_capacity,
  price_month_cents    = excluded.price_month_cents,
  price_quarter_cents  = excluded.price_quarter_cents,
  price_halfyear_cents = excluded.price_halfyear_cents,
  price_year_cents     = excluded.price_year_cents,
  capabilities         = excluded.capabilities;
