// AUTO-GENERATED by scripts/gen-trainer-map.mjs — do not edit by hand.
//   node scripts/gen-trainer-map.mjs cache --ratio 0.25 --maxerr 4
//
// The mesh at `mesh` carries the map and its collision hull, shaded flat by
// material area (shared/cs3d/flatGreys.js). Metres, y-up.
//
// `collision` is what makes a wallbang possible: the surface under every
// triangle of the hull, and the audience bands, so shared/sim3d/penetration.js
// can charge a bullet by thickness AND material exactly as CS2 does.

export const CACHE_MAP_DATA = {
  "id": "cache",
  "label": "Cache",
  "mesh": "/maps/ported/cache/cache.glb",
  "version": "572766a1",
  "bounds": {
    "minX": -60.909,
    "maxX": 97.536,
    "minY": 38.786,
    "maxY": 65.354,
    "minZ": -84.557,
    "maxZ": 54.331
  },
  "spawns": [
    {
      "pos": [
        80.039,
        41.351,
        -1.582
      ],
      "yaw": 182
    },
    {
      "pos": [
        81.9,
        41.351,
        -3.748
      ],
      "yaw": 182
    },
    {
      "pos": [
        82.744,
        41.351,
        -0.203
      ],
      "yaw": 182
    },
    {
      "pos": [
        80.318,
        41.351,
        0.127
      ],
      "yaw": 182
    },
    {
      "pos": [
        77.261,
        41.351,
        0.535
      ],
      "yaw": 182
    },
    {
      "pos": [
        74.905,
        41.351,
        1.194
      ],
      "yaw": 182
    },
    {
      "pos": [
        76.096,
        41.351,
        4.267
      ],
      "yaw": 182
    },
    {
      "pos": [
        78.594,
        41.351,
        3.876
      ],
      "yaw": 182
    },
    {
      "pos": [
        80.56,
        41.351,
        2.561
      ],
      "yaw": 182
    },
    {
      "pos": [
        74.086,
        41.351,
        -1.763
      ],
      "yaw": 182
    },
    {
      "pos": [
        77.162,
        41.351,
        -1.693
      ],
      "yaw": 182
    },
    {
      "pos": [
        78.175,
        41.351,
        -3.452
      ],
      "yaw": 182
    },
    {
      "pos": [
        81.039,
        41.351,
        -6.392
      ],
      "yaw": 182
    },
    {
      "pos": [
        76.689,
        41.351,
        -5.726
      ],
      "yaw": 182
    },
    {
      "pos": [
        78.198,
        41.351,
        -7.862
      ],
      "yaw": 182
    },
    {
      "pos": [
        74.232,
        41.351,
        -4.208
      ],
      "yaw": 182
    },
    {
      "pos": [
        -40.647,
        41.041,
        -20.188
      ],
      "yaw": 270
    },
    {
      "pos": [
        -36.786,
        41.041,
        -20.188
      ],
      "yaw": 270
    },
    {
      "pos": [
        -35.567,
        41.041,
        -22.22
      ],
      "yaw": 270
    },
    {
      "pos": [
        -37.802,
        41.041,
        -22.22
      ],
      "yaw": 270
    },
    {
      "pos": [
        -39.631,
        41.041,
        -22.22
      ],
      "yaw": 270
    },
    {
      "pos": [
        -41.866,
        41.041,
        -22.22
      ],
      "yaw": 270
    },
    {
      "pos": [
        -41.866,
        41.041,
        -17.953
      ],
      "yaw": 270
    },
    {
      "pos": [
        -39.631,
        41.041,
        -17.953
      ],
      "yaw": 270
    },
    {
      "pos": [
        -37.802,
        41.041,
        -17.953
      ],
      "yaw": 270
    },
    {
      "pos": [
        -35.567,
        41.041,
        -17.953
      ],
      "yaw": 270
    },
    {
      "pos": [
        -40.647,
        41.041,
        -15.718
      ],
      "yaw": 270
    },
    {
      "pos": [
        -36.786,
        41.041,
        -15.718
      ],
      "yaw": 270
    },
    {
      "pos": [
        -40.647,
        41.041,
        -24.252
      ],
      "yaw": 270
    },
    {
      "pos": [
        -36.786,
        41.041,
        -24.252
      ],
      "yaw": 270
    },
    {
      "pos": [
        -38.717,
        41.041,
        -24.659
      ],
      "yaw": 270
    },
    {
      "pos": [
        -38.717,
        41.041,
        -20.188
      ],
      "yaw": 270
    }
  ],
  "tris": 891756,
  "collisionTris": 459376,
  "collision": {
    "triangles": 459376,
    "surfaces": [
      "wood_tree",
      "metal",
      "wood",
      "rubber",
      "default",
      "metal_sheetmetal",
      "glass",
      "chainlink",
      "plastic",
      "vrf_unknown_key_2214245875",
      "metal_barrel",
      "porcelain",
      "concrete",
      "ladder",
      "vrf_unknown_key_2838185980",
      "metal_ventslat"
    ],
    "bands": [
      [
        0,
        28,
        5,
        0
      ],
      [
        28,
        2558,
        1,
        0
      ],
      [
        2558,
        69095,
        6,
        0
      ],
      [
        69095,
        69983,
        7,
        0
      ],
      [
        69983,
        70167,
        8,
        0
      ],
      [
        70167,
        398039,
        1,
        0
      ],
      [
        398039,
        398305,
        9,
        0
      ],
      [
        398305,
        399187,
        10,
        0
      ],
      [
        399187,
        402021,
        3,
        0
      ],
      [
        402021,
        402389,
        6,
        0
      ],
      [
        402389,
        402487,
        11,
        0
      ],
      [
        402487,
        420240,
        1,
        0
      ],
      [
        420240,
        445200,
        12,
        0
      ],
      [
        445200,
        445204,
        7,
        1
      ],
      [
        445204,
        448498,
        14,
        1
      ],
      [
        448498,
        448514,
        15,
        0
      ],
      [
        448514,
        448530,
        15,
        0
      ],
      [
        448530,
        448766,
        4,
        0
      ],
      [
        448766,
        449050,
        0,
        0
      ],
      [
        449050,
        449122,
        1,
        0
      ],
      [
        449122,
        449446,
        2,
        0
      ],
      [
        449446,
        449608,
        3,
        0
      ],
      [
        449608,
        456149,
        4,
        0
      ],
      [
        456149,
        456151,
        13,
        0
      ],
      [
        456151,
        456223,
        1,
        0
      ],
      [
        456223,
        459214,
        2,
        0
      ],
      [
        459214,
        459376,
        3,
        0
      ]
    ],
    "ranges": {
      "light": [
        [
          0,
          448530
        ]
      ],
      "walk": [
        [
          0,
          456151
        ]
      ],
      "nade": [
        [
          0,
          448530
        ],
        [
          456151,
          459376
        ]
      ]
    }
  }
};
